<?php
// Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink');
define('DB_PASS', 'testlink');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink_1_9_QA_20101107');
define('DB_TABLE_PREFIX', '');
?>